package kobisopenapi.apiservice.server.boxoffice.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;
import kr.or.kobis.kobisopenapi.BoxOfficeAPIService;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-07-04T01:12:58.179+09:00
 * Generated source version: 3.3.7
 *
 */
@WebServiceClient(name = "BoxOfficeAPIServiceImplService",
                  wsdlLocation = "file:/C:/workspace/moviewebservice/src/main/resources/wsdl/boxoffice.wsdl",
                  targetNamespace = "http://service.boxoffice.server.apiservice.kobisopenapi/")
public class BoxOfficeAPIServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.boxoffice.server.apiservice.kobisopenapi/", "BoxOfficeAPIServiceImplService");
    public final static QName BoxOfficeAPIServiceImplPort = new QName("http://service.boxoffice.server.apiservice.kobisopenapi/", "BoxOfficeAPIServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/workspace/moviewebservice/src/main/resources/wsdl/boxoffice.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(BoxOfficeAPIServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO,
                     "Can not initialize the default wsdl from {0}", "file:/C:/workspace/moviewebservice/src/main/resources/wsdl/boxoffice.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public BoxOfficeAPIServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public BoxOfficeAPIServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public BoxOfficeAPIServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }

    public BoxOfficeAPIServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public BoxOfficeAPIServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public BoxOfficeAPIServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }




    /**
     *
     * @return
     *     returns BoxOfficeAPIService
     */
    @WebEndpoint(name = "BoxOfficeAPIServiceImplPort")
    public BoxOfficeAPIService getBoxOfficeAPIServiceImplPort() {
        return super.getPort(BoxOfficeAPIServiceImplPort, BoxOfficeAPIService.class);
    }

    /**
     *
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns BoxOfficeAPIService
     */
    @WebEndpoint(name = "BoxOfficeAPIServiceImplPort")
    public BoxOfficeAPIService getBoxOfficeAPIServiceImplPort(WebServiceFeature... features) {
        return super.getPort(BoxOfficeAPIServiceImplPort, BoxOfficeAPIService.class, features);
    }

}
