package kr.or.kobis.kobisopenapi;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-07-04T01:12:58.174+09:00
 * Generated source version: 3.3.7
 *
 */
@WebService(targetNamespace = "http://www.kobis.or.kr/kobisopenapi", name = "BoxOfficeAPIService")
@XmlSeeAlso({ObjectFactory.class})
public interface BoxOfficeAPIService {

    @WebMethod
    @RequestWrapper(localName = "searchWeeklyBoxOfficeList", targetNamespace = "http://www.kobis.or.kr/kobisopenapi", className = "kr.or.kobis.kobisopenapi.SearchWeeklyBoxOfficeList")
    @ResponseWrapper(localName = "searchWeeklyBoxOfficeListResponse", targetNamespace = "http://www.kobis.or.kr/kobisopenapi", className = "kr.or.kobis.kobisopenapi.SearchWeeklyBoxOfficeListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public kr.or.kobis.kobisopenapi.WeeklyBoxOfficeResult searchWeeklyBoxOfficeList(

        @WebParam(name = "key", targetNamespace = "")
        java.lang.String key,
        @WebParam(name = "targetDt", targetNamespace = "")
        java.lang.String targetDt,
        @WebParam(name = "itemPerPage", targetNamespace = "")
        java.lang.String itemPerPage,
        @WebParam(name = "weekGb", targetNamespace = "")
        java.lang.String weekGb,
        @WebParam(name = "multiMovieYn", targetNamespace = "")
        java.lang.String multiMovieYn,
        @WebParam(name = "repNationCd", targetNamespace = "")
        java.lang.String repNationCd,
        @WebParam(name = "wideAreaCd", targetNamespace = "")
        java.lang.String wideAreaCd
    ) throws OpenAPIFault;

    @WebMethod
    @RequestWrapper(localName = "searchDailyBoxOfficeList", targetNamespace = "http://www.kobis.or.kr/kobisopenapi", className = "kr.or.kobis.kobisopenapi.SearchDailyBoxOfficeList")
    @ResponseWrapper(localName = "searchDailyBoxOfficeListResponse", targetNamespace = "http://www.kobis.or.kr/kobisopenapi", className = "kr.or.kobis.kobisopenapi.SearchDailyBoxOfficeListResponse")
    @WebResult(name = "return", targetNamespace = "")
    public kr.or.kobis.kobisopenapi.DailyBoxOfficeResult searchDailyBoxOfficeList(

        @WebParam(name = "key", targetNamespace = "")
        java.lang.String key,
        @WebParam(name = "targetDt", targetNamespace = "")
        java.lang.String targetDt,
        @WebParam(name = "itemPerPage", targetNamespace = "")
        java.lang.String itemPerPage,
        @WebParam(name = "multiMovieYn", targetNamespace = "")
        java.lang.String multiMovieYn,
        @WebParam(name = "repNationCd", targetNamespace = "")
        java.lang.String repNationCd,
        @WebParam(name = "wideAreaCd", targetNamespace = "")
        java.lang.String wideAreaCd
    ) throws OpenAPIFault;
}
