
package kr.or.kobis.kobisopenapi;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.7
 * 2020-07-04T01:12:58.169+09:00
 * Generated source version: 3.3.7
 */

@WebFault(name = "OpenAPIFault", targetNamespace = "http://www.kobis.or.kr/kobisopenapi")
public class OpenAPIFault extends Exception {

    private kr.or.kobis.kobisopenapi.OpenApiFaultBean openAPIFault;

    public OpenAPIFault() {
        super();
    }

    public OpenAPIFault(String message) {
        super(message);
    }

    public OpenAPIFault(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public OpenAPIFault(String message, kr.or.kobis.kobisopenapi.OpenApiFaultBean openAPIFault) {
        super(message);
        this.openAPIFault = openAPIFault;
    }

    public OpenAPIFault(String message, kr.or.kobis.kobisopenapi.OpenApiFaultBean openAPIFault, java.lang.Throwable cause) {
        super(message, cause);
        this.openAPIFault = openAPIFault;
    }

    public kr.or.kobis.kobisopenapi.OpenApiFaultBean getFaultInfo() {
        return this.openAPIFault;
    }
}
